// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdP2Iks24voKqDSs4rYcrKRL-VbeCOfU',
    appId: '1:47545646262:android:db648613d6218a36d0ba17',
    messagingSenderId: '47545646262',
    projectId: 'team-todo-38f76',
    databaseURL: 'https://team-todo-38f76-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'team-todo-38f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJC5Gh6ReJZ_TvxK3dFizLVA3L77BtslY',
    appId: '1:47545646262:ios:28f60523ad4a393dd0ba17',
    messagingSenderId: '47545646262',
    projectId: 'team-todo-38f76',
    databaseURL: 'https://team-todo-38f76-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'team-todo-38f76.appspot.com',
    iosBundleId: 'com.example.infoHubApp'
    );
}
